// Copyright 2021 Manna Harbour
// https://github.com/manna-harbour/miryoku

#define MIRYOKU_CLIPBOARD_WIN


#define MIRYOKU_LAYER_LIST \
  MIRYOKU_LAYER(MIRYOKU_LAYER_BASE, "Base") \
  MIRYOKU_LAYER(MIRYOKU_LAYER_NAV, "Navigation") \
  MIRYOKU_LAYER(MIRYOKU_LAYER_MOUSE, "Mouse") \
  MIRYOKU_LAYER(MIRYOKU_LAYER_MEDIA, "Media") \
  MIRYOKU_LAYER(MIRYOKU_LAYER_NUM, "Numbers") \
  MIRYOKU_LAYER(MIRYOKU_LAYER_SYM, "Symbols") \
  MIRYOKU_LAYER(MIRYOKU_LAYER_FUN, "Functions")